# -*- coding: utf-8 -*-
"""Диплом Python Воробьёв А.Н..ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12Ew0-AFzeHdC_gA0LW4xChiMq5FrtZxb
"""

import pandas as pd

# 1. загрузка df +5
HR = pd.read_csv('HR.csv')
HR.head()

HR_variables = HR[['satisfaction_level', 'last_evaluation', 'number_project', 'average_montly_hours', 'time_spend_company']]

# 2.Расчет: среднее (mean), мин/макс, медиана (50%), среднее отклонение (std) +10
HR[['satisfaction_level', 'last_evaluation', 'number_project', 'average_montly_hours', 'time_spend_company']].describe ()

""" 3. Рассчитайте и визуализировать корреляционную матрицу для
количественных переменных.
Определите две самые скоррелированные и две наименее
скоррелированные переменные. +10 """
HR.corr()

import seaborn as sns
sns.heatmap(HR.corr())
# максимальная коррелиреляция: average_monthly_hours (кол-во часов на рабочем месте в месяц) /number_projects (кол-во выполненных проектов)
# минимальная корреляция: work_accident (несчастные случаи) / time_spend_company (стаж работы в компании)



# 4. Cколько сотрудников работает в каждом департаменте +5
HR_work_empl = HR.loc[HR.left ==0] # только работающие сотрудники
HR_work_empl.department.value_counts()

# 5. Распределение сотрудников по ЗП +5
HR_work_empl.salary.value_counts()

# 6. Распределение сотрудников по ЗП в каждом департаменте +5
HR_dep_sal = HR_work_empl.groupby(['department', 'salary']).count() 
HR_dep_sal['left']

# 7. Проверка гипотезы, что сотрудники с высоким окладом проводят на работе больше времени, чем с низким
# Гипотеза подтверждена +10. Проверка на работающих сотрудниках.
HR_sal_hours = HR_work_empl.groupby('salary').mean() #расчитываем среднее значение по всем столбцам
HR_sal_hours['average_montly_hours'] #отображаем среднее значение по ЗП

"""8. Рассчитать следующие показатели среди уволившихся и не
уволившихся сотрудников (по отдельности):
- Средняя степень удовлетворенности
- Среднее количество проектов"""

HR_group= HR.groupby('left').agg({'satisfaction_level': 'mean', 'number_project': 'mean', 'promotion_last_5years': ['sum', len] })
HR_group

# 8. Доля сотрудников с повышением за последние 5 лет +10
HR_group ['boosting_last_5years'] = HR_group['promotion_last_5years']['sum']/ HR_group['promotion_last_5years']['len']

HR_group [['satisfaction_level','number_project', 'boosting_last_5years']]